services:
  taskmanapi:
    image: taskmanapi
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
      - "8081:8081"


    depends_on:
      - postgresql

  postgresql:
    image: postgres:13
    environment:
      # HACK: This is a placeholder, absolutely not secure
      # TODO: Use a secret manager
      POSTGRES_USER: taskman
      POSTGRES_PASSWORD: taskman
      POSTGRES_DB: taskman
    ports:
      - "5432:5432"
