@startuml
class NotificationsController {
    + NotificationsController(context:DefaultContext)
    + <<async>> GetNotifications() : Task<ActionResult<IEnumerable<Notification>>>
    + <<async>> GetNotification(id:int) : Task<ActionResult<Notification>>
    + <<async>> PutNotification(id:int, notification:Notification) : Task<IActionResult>
    + <<async>> PostNotification(notification:Notification) : Task<ActionResult<Notification>>
    + <<async>> DeleteNotification(id:int) : Task<IActionResult>
}
ControllerBase <|-- NotificationsController
@enduml
