@startuml
class Project {
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
}

Project "1" --> "0..*" ProjTask : project divided in tasks
@enduml
